// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Crypton.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class SeedData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "item_type",
                columns: new[] { "id", "max_rarity", "min_rarity", "name", "price" },
                values: new object[,]
                {
                    { "AMETHYST", 0.9f, 0.1f, "Amethyst 🔴", 40m },
                    { "BEAR", 0.9f, 0.1f, "Bear 🦌", 20m },
                    { "COMMON_FISH", 0.9f, 0.1f, "Common Fish 🐟", 5m },
                    { "COPPER_COIN", 0.9f, 0.1f, "Copper Coin 🐘", 1m },
                    { "DEER", 0.9f, 0.1f, "Deer 🐷", 10m },
                    { "DIAMOND", 0.9f, 0.1f, "Diamond 💎", 50m },
                    { "ELEPHANT", 0.9f, 0.1f, "Elephant 🐯", 60m },
                    { "EMERALD", 0.9f, 0.1f, "Emerald 👛", 10m },
                    { "FISHING_ROD", 0.9f, 0.1f, "Fishing rod 🎣", 75m },
                    { "GOLDEN_FISH", 0.9f, 0.1f, "Golden Fish 🦈", 50m },
                    { "HUNTING_RIFLE", 0.9f, 0.1f, "Hunting Rifle 🔫", 75m },
                    { "KNIFE", 0.9f, 0.1f, "Knife 🔪", 50m },
                    { "LION", 0.9f, 0.1f, "Lion 🦁", 50m },
                    { "PIG", 0.9f, 0.1f, "Pig 🥇🐟", 5m },
                    { "RARE_FISH", 0.9f, 0.1f, "Rare Fish 🐡", 10m },
                    { "RUBY", 0.9f, 0.1f, "Ruby 🔶", 20m },
                    { "SAPPHIRE", 0.9f, 0.1f, "Sapphire 🔷", 30m },
                    { "SHARK", 0.9f, 0.1f, "Shark 🐠", 40m },
                    { "SHOVEL", 0.9f, 0.1f, "Shovel 🪣", 75m },
                    { "TIGER", 0.9f, 0.1f, "Tiger 🐻", 40m },
                    { "TROPICAL_FISH", 0.9f, 0.1f, "Tropical Fish 🐯", 20m },
                    { "WEDDING_RING", 0.9f, 0.1f, "Wedding Ring 💍", 1000m },
                    { "WOLF", 0.9f, 0.1f, "Wolf 🐺", 30m }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "AMETHYST");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "BEAR");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "COMMON_FISH");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "COPPER_COIN");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "DEER");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "DIAMOND");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "ELEPHANT");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "EMERALD");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "FISHING_ROD");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "GOLDEN_FISH");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "HUNTING_RIFLE");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "KNIFE");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "LION");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "PIG");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "RARE_FISH");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "RUBY");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "SAPPHIRE");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "SHARK");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "SHOVEL");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "TIGER");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "TROPICAL_FISH");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "WEDDING_RING");

            migrationBuilder.DeleteData(
                table: "item_type",
                keyColumn: "id",
                keyValue: "WOLF");
        }
    }
}
